-- ============================================================================
-- DATABASE DUMP: OOH STRATEGIC PLANNER (CV BANDUNG MEDIA OUTDOOR)
-- Format: SQLite 3
-- Engine: Server-side Persistent Database
-- ============================================================================

PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS mobility_corridors;
CREATE TABLE mobility_corridors (
  corridor_id TEXT PRIMARY KEY,
  corridor_name TEXT NOT NULL,
  corridor_type TEXT NOT NULL,
  start_point_name TEXT,
  end_point_name TEXT,
  avg_speed_kmh REAL DEFAULT 25.0,
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS points_of_interest;
CREATE TABLE points_of_interest (
  poi_id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  target_ses TEXT DEFAULT 'SES A/B',
  highlight_text TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS billboard_spots;
CREATE TABLE billboard_spots (
  spot_id TEXT PRIMARY KEY,
  spot_code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  regency TEXT NOT NULL,
  district TEXT,
  address TEXT NOT NULL,
  road_name TEXT NOT NULL,
  road_type TEXT NOT NULL,
  corridor_type TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  media_type TEXT NOT NULL,
  width_m REAL NOT NULL,
  height_m REAL NOT NULL,
  area_m2 REAL NOT NULL,
  sides INTEGER DEFAULT 1,
  orientation TEXT,
  viewing_distance_m INTEGER DEFAULT 200,
  daily_gross_reach INTEGER NOT NULL,
  vac_daily INTEGER NOT NULL,
  avg_dwell_time_sec INTEGER NOT NULL DEFAULT 40,
  avg_speed_kmh INTEGER NOT NULL DEFAULT 25,
  visibility_score INTEGER NOT NULL DEFAULT 90,
  effectiveness_score INTEGER NOT NULL DEFAULT 90,
  clutter_level TEXT DEFAULT 'Sedang (Normal)',
  occupancy_status TEXT NOT NULL DEFAULT 'Available',
  current_brand TEXT,
  rate_per_month_idr INTEGER NOT NULL,
  cpm_idr INTEGER NOT NULL,
  lighting_type TEXT,
  facing_direction TEXT,
  target_demographics TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS spot_poi_distances;
CREATE TABLE spot_poi_distances (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  spot_id TEXT NOT NULL,
  poi_id TEXT NOT NULL,
  distance_meters INTEGER NOT NULL,
  highlight_text TEXT
);

DROP TABLE IF EXISTS campaign_plans;
CREATE TABLE campaign_plans (
  plan_id TEXT PRIMARY KEY,
  client_name TEXT NOT NULL,
  campaign_title TEXT NOT NULL,
  industry_category TEXT,
  budget_millions INTEGER NOT NULL,
  duration_months INTEGER NOT NULL DEFAULT 1,
  target_corridor TEXT DEFAULT 'Semua Jalur',
  target_ses TEXT DEFAULT 'SES A, SES B',
  is_domination_journey INTEGER DEFAULT 0,
  total_cost_millions REAL NOT NULL,
  total_monthly_vac INTEGER NOT NULL,
  total_gross_reach INTEGER NOT NULL,
  blended_cpm INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS campaign_route_waypoints;
CREATE TABLE campaign_route_waypoints (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  plan_id TEXT NOT NULL,
  spot_id TEXT NOT NULL,
  sequence_order INTEGER NOT NULL,
  distance_from_prev_km REAL DEFAULT 0.0,
  travel_time_from_prev_min INTEGER DEFAULT 0,
  leg_road_name TEXT
);

INSERT INTO mobility_corridors (corridor_id, corridor_name, corridor_type, start_point_name, end_point_name, avg_speed_kmh, description) VALUES ('corridor-komuter', 'Jalur Komuter (Daily Commuters)', 'Jalur Komuter', 'Gerbang Tol Pasteur / Cileunyi', 'Pusat Kota Bandung & Wilayah Komuter', 28, 'Jalur pergerakan harian pekerja & pebisnis komuter antar-kota dan pusat kota');
INSERT INTO mobility_corridors (corridor_id, corridor_name, corridor_type, start_point_name, end_point_name, avg_speed_kmh, description) VALUES ('corridor-pariwisata', 'Jalur Pariwisata (Leisure & Tourism)', 'Jalur Pariwisata', 'Jl. Setiabudi / Tol Soreang', 'Kawasan Wisata Lembang & Ciwidey', 20, 'Jalur utama wisatawan domestik menuju objek wisata alam pegunungan');
INSERT INTO mobility_corridors (corridor_id, corridor_name, corridor_type, start_point_name, end_point_name, avg_speed_kmh, description) VALUES ('corridor-komersial', 'Jalur Komersial & Retail (Premium Areas)', 'Jalur Komersial & Retail', 'Jl. Ir. H. Djuanda (Dago)', 'Jl. R.E. Martadinata & Kawasan Bisnis Asia Afrika', 16, 'Jantung retail, pusat perbelanjaan, factory outlet, kafe & perbankan bergengsi');
INSERT INTO mobility_corridors (corridor_id, corridor_name, corridor_type, start_point_name, end_point_name, avg_speed_kmh, description) VALUES ('corridor-logistik', 'Jalur Logistik & Industri', 'Jalur Logistik & Industri', 'Kawasan Industri KIIC / Tol Cipularang', 'By-Pass Soekarno Hatta & Sentra Manufaktur', 35, 'Arteri distribusi barang, armada truk logistik nasional & pergudangan');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-01', 'JBR-BDG-001', 'Simpang Lima Asia Afrika Curved LED', 'Kota Bandung', 'Sumur Bandung', 'Jl. Asia Afrika No. 120 (Simpang Lima Sunda - Asia Afrika)', 'Jl. Asia Afrika / Simpang Lima', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.9213, 107.6186, 'LED Videotron', 24, 12, 288, 1, 'Curved Corner (Sudut Simpang)', 220, 245000, 218000, 52, 14, 96, 94, 'Sedang (Normal)', 'Occupied', 'Bank BJB Digital Banking', 165000000, 22400, 'P6 Ultra-Bright SMD LED Full RGB', 'Arus Sudirman & Gatot Subroto menuju Alun-Alun Bandung', 'Urban Professionals, Eksekutif Finansial, Wisatawan Domestik');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-02', 'JBR-BDG-002', 'Gerbang Tol Pasteur Exit Gateway', 'Kota Bandung', 'Sukajadi', 'Jl. Dr. Djunjunan (Pasteur) KM 0.5 Arah Pusat Kota', 'Jl. Dr. Djunjunan (Pasteur Exit Tol)', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.8924, 107.5794, 'Megatron', 20, 10, 200, 1, 'Front Facing (Tegak Lurus)', 350, 285000, 259000, 42, 28, 98, 96, 'Rendah (Unobstructed)', 'Occupied', 'Telkomsel 5G Hypernet', 195000000, 22800, 'P8 Outdoor High-Contrast Videotron', 'Keluar Gerbang Tol Pasteur menuju Jl. Layang Pasupati & Gasibu', 'Wisatawan Jakarta-Bandung, Pebisnis Komuter, Pemilik Mobil Pribadi');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-03', 'JBR-BDG-003', 'Dago Simpang McDonald Landmark LED', 'Kota Bandung', 'Coblong', 'Jl. Ir. H. Juanda No. 154 (Simpang Dago Cikapayang Bawah)', 'Jl. Ir. H. Juanda (Dago)', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komersial & Retail (Premium Areas)', -6.8863, 107.6149, 'LED Videotron', 16, 8, 128, 1, 'Front Facing (Tegak Lurus)', 180, 178000, 156000, 48, 16, 93, 91, 'Sedang (Normal)', 'Occupied', 'Shopee Garansi Tepat Waktu', 120000000, 22400, 'P6 SMD LED 6500 nits', 'Arus Dago Atas & Cikapayang Flyover', 'Gen-Z, Mahasiswa ITB/UNPAD, Komunitas Gaya Hidup & Kafe');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-04', 'JBR-BDG-004', 'Riau Junction Simpang Trunojoyo Billboard', 'Kota Bandung', 'Bandung Wetan', 'Jl. R.E. Martadinata (Riau) No. 42', 'Jl. R.E. Martadinata', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komersial & Retail (Premium Areas)', -6.9084, 107.6138, 'Static Billboard', 12, 6, 72, 2, 'Double Sided (Dua Sisi)', 150, 142000, 118000, 36, 18, 89, 86, 'Sedang (Normal)', 'Available', '', 65000000, 15200, 'Frontlite High-Lumen Metal Halide 8x400W', 'Dua arah Jl. Riau (Factory Outlet & Heritage Zone)', 'Shoppers, Wisata Belanja, Family Dining');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-05', 'JBR-BDG-005', 'Simpang Buah Batu Exit Tol Purbaleunyi', 'Kota Bandung', 'Bandung Kidul', 'Jl. Buah Batu Dekat Gerbang Tol KM 142', 'Jl. Terusan Buah Batu', 'Arteri Sekunder', 'Jalur Komuter (Daily Commuters)', -6.9632, 107.6394, 'Static Billboard', 16, 8, 128, 1, 'Front Facing (Tegak Lurus)', 260, 195000, 168000, 58, 12, 92, 89, 'Sedang (Normal)', 'Occupied', 'Gojek Pasti Ada Jalan', 85000000, 14500, 'Backlite LED Uniform Grid 120W x 10', 'Keluar Exit Tol Buah Batu menuju Pusat Kota & Dayeuhkolot', 'Komuter Bandung Selatan, Mahasiswa Telkom University, Residensial');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-06', 'JBR-BDG-006', 'Pasirkaliki 23 Paskal Mall Vertical LED', 'Kota Bandung', 'Andir', 'Jl. Pasirkaliki No. 25-27 (Akses Utama 23 Paskal)', 'Jl. Pasirkaliki', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komersial & Retail (Premium Areas)', -6.9149, 107.5996, 'LED Videotron', 8, 16, 128, 1, 'Front Facing (Tegak Lurus)', 140, 162000, 144000, 46, 15, 94, 88, 'Tinggi (Kompetitif)', 'Reserved', 'Samsung Galaxy Z Fold', 135000000, 27700, 'P4 Indoor/Outdoor High Definition LED', 'Arus Stasiun Bandung menuju PVJ & Sukajadi', 'Middle-Up Urbanites, Mall Visitors, Gadget Enthusiasts');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-07', 'JBR-BDG-007', 'Flyover Pasupati Cikapayang Iconic Bridge JPO', 'Kota Bandung', 'Coblong', 'Jl. Layang Prof. Mochtar Kusumaatmadja (Pasupati)', 'Flyover Pasupati', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.8996, 107.6105, 'JPO Pedestrian Bridge', 28, 4, 112, 2, 'Cantilever Overhead', 300, 230000, 205000, 25, 45, 97, 93, 'Rendah (Unobstructed)', 'Occupied', 'Indosat Ooredoo Hutchison', 110000000, 16000, 'LED Strip Contour + Floodlight 500W', 'Arus Timur-Barat & Barat-Timur Layang Pasupati', 'Komuter Lintas Kota Bandung, Penglaju Pasteur-Surapati');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-08', 'JBR-BDG-008', 'Jl. Soekarno Hatta MTC Metro Indah Megatron', 'Kota Bandung', 'Rancasari', 'Jl. Soekarno Hatta No. 590 (Depan Kawasan Bisnis MTC)', 'By-Pass Jl. Soekarno Hatta', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.9421, 107.6622, 'Megatron', 18, 9, 162, 1, 'Front Facing (Tegak Lurus)', 280, 215000, 182000, 38, 35, 91, 87, 'Sedang (Normal)', 'Available', '', 95000000, 14700, 'P8 Outdoor High-Res Videotron', 'Arus By-Pass Kiaracondong menuju Cibiru & Cileunyi', 'Komuter Bandung Timur, Pengguna Jalur Antarkota, Pekerja Kawasan Bisnis');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-09', 'JBR-BKS-001', 'Flyover Summarecon Bekasi Iconic Videotron', 'Kota Bekasi', 'Bekasi Utara', 'Jl. Jendral Ahmad Yani - Flyover KH Noer Ali Summarecon', 'Jl. Jend. Ahmad Yani', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.2285, 106.9992, 'LED Videotron', 25, 10, 250, 1, 'Curved Corner (Sudut Simpang)', 320, 310000, 285000, 62, 18, 98, 97, 'Sedang (Normal)', 'Occupied', 'Hyundai IONIQ 5 Electric', 210000000, 22500, 'P6 Ultra Dynamic Curve Display', 'Keluar Pintu Tol Bekasi Barat menuju Summarecon & Harapan Baru', 'Keluarga Mapan, Executive Jabodetabek, Automotive Buyers');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-10', 'JBR-BKS-002', 'Tol Jakarta - Cikampek KM 14 Gantry Megatron', 'Kota Bekasi', 'Bekasi Barat', 'Ruas Jalan Tol Jakarta-Cikampek KM 14+200', 'Jalan Tol Jakarta - Cikampek', 'Jalan Tol Bebas Hambatan', 'Jalur Komuter (Daily Commuters)', -6.252, 106.984, 'Megatron', 30, 12, 360, 2, 'Cantilever Overhead', 500, 430000, 395000, 22, 65, 99, 95, 'Rendah (Unobstructed)', 'Occupied', 'Pertamax Green 95 Energy', 275000000, 21300, 'P10 Highway Rugged LED Display', 'Dua arah Tol Japek: Arah Cikampek/Jawa & Arah Cawang/Jakarta', 'Pebisnis Tol Trans Jawa, Logistik Nasional, Turis Liburan');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-11', 'JBR-BKS-003', 'Kalimalang Metropolitan Mall JPO Display', 'Kota Bekasi', 'Bekasi Selatan', 'Jl. KH. Noer Ali (Kalimalang) Simpang MM Mall', 'Jl. KH. Noer Ali (Kalimalang)', 'Arteri Primer', 'Jalur Komersial & Retail (Premium Areas)', -6.2483, 106.9922, 'JPO Pedestrian Bridge', 22, 4.5, 99, 2, 'Cantilever Overhead', 200, 225000, 195000, 44, 20, 92, 89, 'Tinggi (Kompetitif)', 'Available', '', 88000000, 13000, 'Backlight LED Module 960W Total', 'Arus Becakayu & Kalimalang menuju Tol Bekasi Barat', 'Pekerja Komuter Jakarta-Bekasi, Pengunjung Mall');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-12', 'JBR-BKS-004', 'Boulevard Harapan Indah Gateway Billboard', 'Kota Bekasi', 'Medan Satria', 'Bundaran Gerbang Utama Kota Harapan Indah', 'Jl. Boulevard Harapan Indah', 'Kolektor Perkotaan', 'Jalur Komuter (Daily Commuters)', -6.184, 106.9772, 'Static Billboard', 14, 7, 98, 1, 'Front Facing (Tegak Lurus)', 240, 155000, 132000, 35, 25, 88, 85, 'Rendah (Unobstructed)', 'Occupied', 'Mayora Kopi Kenangan', 58000000, 12500, 'Spotlight LED Lumileds 6x200W', 'Pintu Gerbang Harapan Indah dari Jl. Raya Sultan Agung', 'Keluarga Residensial Modern, Konsumen FMCG');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-13', 'JBR-BGR-001', 'Tugu Kujang Baranangsiang Iconic Landmark LED', 'Kota Bogor', 'Bogor Tengah', 'Simpang Tugu Kujang - Jl. Pajajaran / Jl. Otto Iskandardinata', 'Jl. Pajajaran (Simpang Tugu Kujang)', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.6015, 106.8049, 'LED Videotron', 18, 9, 162, 1, 'Curved Corner (Sudut Simpang)', 250, 240000, 215000, 54, 15, 97, 95, 'Sedang (Normal)', 'Occupied', 'Bank Mandiri Livin', 145000000, 20100, 'P6 SMD LED Vivid 7000 nits', 'Keluar Terminal Baranangsiang & Tol Jagorawi arah Istana Bogor', 'Wisatawan Kebun Raya, Komuter Kereta/Tol, Mahasiswa IPB');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-14', 'JBR-BGR-002', 'Ciawi Exit Tol Jagorawi Pintu Masuk Puncak', 'Kabupaten Bogor', 'Ciawi', 'Simpang Ciawi Simpang Gadog KM 45', 'Jl. Raya Ciawi - Puncak', 'Arteri Primer', 'Jalur Pariwisata (Leisure & Tourism)', -6.6631, 106.8574, 'Megatron', 22, 10, 220, 1, 'Front Facing (Tegak Lurus)', 380, 260000, 232000, 72, 10, 95, 94, 'Tinggi (Kompetitif)', 'Occupied', 'Teh Botol Sosro Nusantara', 155000000, 19800, 'P8 Outdoor Anti-Fog Videotron', 'Kendaraan dari Exit Tol Jagorawi Ciawi mendaki jalur Puncak', 'Wisatawan Akhir Pekan Jabodetabek, Turis Keluarga, Kuliner');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-15', 'JBR-BGR-003', 'Botani Square Pajajaran Premium Billboard', 'Kota Bogor', 'Bogor Timur', 'Jl. Pajajaran Dekat Akses Botani Square Mall & IPB Baranangsiang', 'Jl. Raya Pajajaran', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komersial & Retail (Premium Areas)', -6.5982, 106.8088, 'Static Billboard', 14, 7, 98, 1, 'Front Facing (Tegak Lurus)', 190, 172000, 148000, 38, 20, 91, 88, 'Sedang (Normal)', 'Available', '', 68000000, 13200, 'Metal Halide Floodlight 6x400W', 'Arus Pajajaran dari Warung Jambu menuju Sukasari', 'Mall Visitors, Akademisi IPB, Komunitas Kafe Pajajaran');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-16', 'JBR-BGR-004', 'Sholeh Iskandar Flyover Yasmin JPO', 'Kota Bogor', 'Tanah Sareal', 'Jl. KH. R. Abdullah Bin Nuh (Taman Yasmin)', 'Jl. Sholeh Iskandar (BORR Outer Ring Road)', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.5562, 106.7794, 'JPO Pedestrian Bridge', 24, 4, 96, 2, 'Cantilever Overhead', 260, 198000, 174000, 30, 35, 90, 86, 'Sedang (Normal)', 'Occupied', 'Daihatsu Sahabat Petualang', 72000000, 12100, 'Backlite LED Uniform Strip', 'Arus Parung-Bogor & Akses Tol BORR Sentul', 'Penglaju Parung/Bogor Barat, Pengguna Tol BORR');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-17', 'JBR-DPK-001', 'Margonda Raya Margo City LED Spectacular', 'Kota Depok', 'Beji', 'Jl. Margonda Raya No. 358 (Depan Margo City & Detos)', 'Jl. Margonda Raya', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komersial & Retail (Premium Areas)', -6.3725, 106.8322, 'LED Videotron', 20, 10, 200, 1, 'Front Facing (Tegak Lurus)', 240, 265000, 238000, 58, 12, 96, 92, 'Tinggi (Kompetitif)', 'Occupied', 'Gopay Pinjam Finansial', 150000000, 18900, 'P6 Ultra Vibrant LED 6800 nits', 'Arus Jakarta/Pasar Minggu menuju Balai Kota Depok & Sawangan', 'Mahasiswa UI, Gunadarma, Komuter KRL & Mall Shoppers');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-18', 'JBR-DPK-002', 'Jl. Ir. H. Juanda Simpang Margonda Billboard', 'Kota Depok', 'Sukmajaya', 'Jl. Ir. H. Juanda (Akses Tol Cijago KM 1.2)', 'Jl. Ir. H. Juanda', 'Arteri Primer', 'Jalur Komersial & Retail (Premium Areas)', -6.3842, 106.8405, 'Static Billboard', 16, 8, 128, 1, 'Front Facing (Tegak Lurus)', 280, 182000, 154000, 40, 30, 92, 87, 'Sedang (Normal)', 'Available', '', 68000000, 12400, 'LED Floodlight 8x250W', 'Keluar Gerbang Tol Kukusan/Cijago menuju Jl. Raya Bogor', 'Pengguna Tol Cinere-Jagorawi, Residensial Depok Timur');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-19', 'JBR-CRB-001', 'Kartini CSB Mall Curved Videotron', 'Kota Cirebon', 'Kesambi', 'Jl. Dr. Cipto Mangunkusumo - Simpang CSB Mall', 'Jl. Dr. Cipto Mangunkusumo', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komersial & Retail (Premium Areas)', -6.7214, 108.5492, 'LED Videotron', 16, 8, 128, 1, 'Curved Corner (Sudut Simpang)', 180, 155000, 135000, 50, 16, 94, 91, 'Sedang (Normal)', 'Occupied', 'Djarum Super Kretek', 85000000, 18300, 'P6 SMD LED HD Display', 'Arus simpang Cipto menuju Kartini & Grage Mall', 'Masyarakat Pantura, Pebisnis Cirebon-Kuningan, Mall Goers');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-20', 'JBR-CRB-002', 'Tuparev Arteri Cirebon-Kedawung Billboard', 'Kabupaten Cirebon', 'Kedawung', 'Jl. Tuparev No. 88 (Pusat Kuliner Empal Gentong & Hotel)', 'Jl. Raya Tuparev', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.7163, 108.534, 'Static Billboard', 12, 6, 72, 2, 'Double Sided (Dua Sisi)', 200, 128000, 105000, 36, 24, 89, 84, 'Sedang (Normal)', 'Available', '', 42000000, 10900, 'Frontlite Spotlight LED 6x200W', 'Dua arah: Kota Cirebon ke Kedawung & Exit Tol Plumbon', 'Wisatawan Kuliner, Tamu Hotel Tuparev, Komuter Lokal');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-21', 'JBR-CRB-003', 'Tol Palimanan - Kanci KM 208 Gantry Megatron', 'Kabupaten Cirebon', 'Astanajapura', 'Ruas Tol Palikanci KM 208+400', 'Jalan Tol Palimanan - Kanci', 'Jalan Tol Bebas Hambatan', 'Jalur Komuter (Daily Commuters)', -6.7725, 108.618, 'Megatron', 24, 10, 240, 2, 'Cantilever Overhead', 450, 240000, 216000, 20, 75, 97, 90, 'Rendah (Unobstructed)', 'Occupied', 'Oppo Reno Series 5G', 125000000, 17400, 'P10 Rugged Weatherproof LED', 'Arah Jakarta ke Jawa Tengah / Surabaya & Arah Sebaliknya', 'Pemudik & Pelintas Trans Jawa, Armada Ekspedisi, Wisatawan');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-22', 'JBR-KRW-001', 'Tol Jakarta-Cikampek KM 54 Karawang Timur Megatron', 'Kabupaten Karawang', 'Klari', 'Rest Area KM 57 / KM 54 Akses Industri', 'Jalan Tol Jakarta - Cikampek', 'Jalan Tol Bebas Hambatan', 'Jalur Logistik & Industri', -6.3685, 107.3512, 'Megatron', 28, 12, 336, 2, 'Front Facing (Tegak Lurus)', 480, 360000, 325000, 25, 60, 98, 94, 'Rendah (Unobstructed)', 'Occupied', 'Toyota Innova Zenix Hybrid', 185000000, 17100, 'P10 High-Luminance Highway Board', 'Arus Tol Japek arah Cikampek / Tol Cipali & Purbaleunyi', 'Pebisnis Industri Karawang, Wisatawan Lintas Jawa');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-23', 'JBR-KRW-002', 'Bundaran Badami Karawang Barat Videotron', 'Kabupaten Karawang', 'Telukjambe Timur', 'Jl. Interchange Tol Karawang Barat (Kawasan KIIC)', 'Jl. Interchange Karawang Barat', 'Arteri Primer', 'Jalur Logistik & Industri', -6.3328, 107.2842, 'LED Videotron', 16, 8, 128, 1, 'Curved Corner (Sudut Simpang)', 220, 175000, 152000, 52, 18, 93, 90, 'Rendah (Unobstructed)', 'Available', '', 92000000, 17500, 'P6 Outdoor IP65 Certified LED', 'Keluar Tol Karawang Barat menuju Kawasan Industri KIIC & Sedana', 'Ekspatriat Industri Jepang/Korea, Direksi Pabrik, Pekerja Manufaktur');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-24', 'JBR-TSM-001', 'Jl. HZ Mustofa Pusat Bisnis Videotron', 'Kota Tasikmalaya', 'Cihideung', 'Jl. HZ. Mustofa No. 115 (Pusat Retail & Perbankan)', 'Jl. HZ. Mustofa', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komuter (Daily Commuters)', -7.3315, 108.2198, 'LED Videotron', 14, 7, 98, 1, 'Front Facing (Tegak Lurus)', 160, 135000, 118000, 46, 15, 92, 88, 'Sedang (Normal)', 'Occupied', 'Yamaha NMAX Turbo', 65000000, 16000, 'P6 SMD LED Crisp Display', 'Arus utama pusat pertokoan HZ Mustofa arah Simpang Padayungan', 'Konsumen Priangan Timur, Pelaku UMKM Bordir/Batik, Keluarga');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-25', 'JBR-TSM-002', 'Simpang Lima Tasikmalaya Megatron Arteri', 'Kota Tasikmalaya', 'Cipedes', 'Simpang Lima (Pertemuan Jl. Djuanda, RE Martadinata, Mitrabatik)', 'Simpang Lima Tasikmalaya', 'Arteri Primer', 'Jalur Komersial & Retail (Premium Areas)', -7.3192, 108.2235, 'Static Billboard', 16, 8, 128, 1, 'Curved Corner (Sudut Simpang)', 220, 148000, 122000, 55, 14, 91, 86, 'Sedang (Normal)', 'Available', '', 45000000, 10100, 'High-Power LED Floodlights 6x300W', 'Pertemuan arus dari arah Bandung/Ciawi & Ciamis/Pangandaran', 'Pelintas Jalur Selatan Jabar, Warga Kota Tasikmalaya');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-26', 'JBR-SKB-001', 'Jl. Siliwangi Alun-Alun Sukabumi LED', 'Kota Sukabumi', 'Cikole', 'Jl. Siliwangi No. 45 (Dekat Lapang Merdeka)', 'Jl. Siliwangi', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komersial & Retail (Premium Areas)', -6.9248, 106.9284, 'LED Videotron', 12, 6, 72, 1, 'Front Facing (Tegak Lurus)', 150, 115000, 98000, 42, 16, 90, 85, 'Sedang (Normal)', 'Occupied', 'Aqua Danone Konservasi Jabar', 52000000, 15100, 'P6 SMD LED Outdoor 6000 nits', 'Pusat kota Sukabumi arah Salabintana & Balai Kota', 'Masyarakat Sukabumi Kota, Wisatawan Salabintana');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-27', 'JBR-SKB-002', 'Tol Bocimi Exit Cigombong / Parungkuda Billboard', 'Kabupaten Sukabumi', 'Cicurug', 'Akses Keluar Tol Bocimi Ruas Cigombong - Cibadak', 'Jalan Tol Bogor-Ciawi-Sukabumi (Bocimi)', 'Jalan Tol Bebas Hambatan', 'Jalur Komuter (Daily Commuters)', -6.829, 106.821, 'Static Billboard', 18, 8, 144, 1, 'Front Facing (Tegak Lurus)', 320, 145000, 126000, 32, 50, 94, 89, 'Rendah (Unobstructed)', 'Available', '', 55000000, 12600, 'LED Floodlight 6x250W Solar Supported', 'Kendaraan keluar Tol Bocimi menuju Sukabumi & Pelabuhan Ratu', 'Wisatawan Geopark Ciletuh, Truk Pabrik Air Minum & Garmen');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-28', 'JBR-CMH-001', 'Baros Exit Tol Purbaleunyi Cimahi Videotron', 'Kota Cimahi', 'Cimahi Tengah', 'Jl. HMS Mintaredja SH Simpang Baros', 'Jl. Baros (Exit Tol Cimahi)', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -6.8925, 107.5385, 'LED Videotron', 14, 7, 98, 1, 'Curved Corner (Sudut Simpang)', 200, 168000, 146000, 52, 15, 93, 89, 'Sedang (Normal)', 'Occupied', 'Wardah Cosmetics Nature', 78000000, 15500, 'P6 SMD LED Screen', 'Keluar Exit Tol Baros menuju Alun-alun Cimahi & Padalarang', 'Pekerja Industri Kreatif Cimahi, Personel Militer, Komuter');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-29', 'JBR-PWK-001', 'Tol Cipularang KM 88 Rest Area Megatron', 'Kabupaten Purwakarta', 'Sukatani', 'Rest Area Tol Cipularang KM 88+200 Arah Bandung', 'Jalan Tol Cikampek - Purwakarta - Padalarang (Cipularang)', 'Jalan Tol Bebas Hambatan', 'Jalur Komuter (Daily Commuters)', -6.643, 107.411, 'Megatron', 24, 10, 240, 1, 'Front Facing (Tegak Lurus)', 420, 275000, 248000, 45, 40, 97, 93, 'Rendah (Unobstructed)', 'Occupied', 'Kopi Kenangan Rest Area', 140000000, 17000, 'P10 Weather-Resistant LED', 'Memasuki Rest Area KM 88 Arah Bandung & Arus Tol Utama', 'Wisatawan Jakarta ke Bandung, Keluarga, Pebisnis Komuter');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-30', 'JBR-SBG-001', 'Tol Cipali KM 92 Subang Gateway Billboard', 'Kabupaten Subang', 'Kalijati', 'Tol Cikopo - Palimanan KM 92', 'Jalan Tol Cipali (Trans Jawa)', 'Jalan Tol Bebas Hambatan', 'Jalur Komuter (Daily Commuters)', -6.495, 107.674, 'Static Billboard', 20, 8, 160, 2, 'Double Sided (Dua Sisi)', 400, 210000, 185000, 20, 80, 95, 87, 'Rendah (Unobstructed)', 'Available', '', 75000000, 11900, 'Solar Powered LED Floodlights 8x150W', 'Dua arah Tol Cipali: Menuju Cirebon/Jawa & Menuju Jakarta', 'Pengendara Jarak Jauh Trans Jawa, Sopir Bus & Truk Logistik');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-31', 'JBR-SMD-001', 'Jatinangor ITB / UNPAD Campus Corridor LED', 'Kabupaten Sumedang', 'Jatinangor', 'Jl. Raya Bandung-Sumedang KM 21 (Depan Jatos & Kampus)', 'Jl. Raya Jatinangor', 'Kawasan Komersial & Pusat Bisnis', 'Jalur Komuter (Daily Commuters)', -6.9315, 107.7735, 'LED Videotron', 14, 7, 98, 1, 'Front Facing (Tegak Lurus)', 170, 145000, 128000, 48, 14, 92, 89, 'Sedang (Normal)', 'Occupied', 'By.U Telkomsel Anak Muda', 68000000, 15600, 'P6 Full HD LED Display', 'Keluar Gerbang Tol Cileunyi/Cisumdawu menuju Kampus Unpad/ITB', 'Mahasiswa, Civitas Akademika Unpad/ITB/IPDN, Remaja');
INSERT INTO billboard_spots (spot_id, spot_code, name, regency, district, address, road_name, road_type, corridor_type, latitude, longitude, media_type, width_m, height_m, area_m2, sides, orientation, viewing_distance_m, daily_gross_reach, vac_daily, avg_dwell_time_sec, avg_speed_kmh, visibility_score, effectiveness_score, clutter_level, occupancy_status, current_brand, rate_per_month_idr, cpm_idr, lighting_type, facing_direction, target_demographics) VALUES ('spot-32', 'JBR-GRT-001', 'Jl. Cimanuk Simpang Tarogong Garut Billboard', 'Kabupaten Garut', 'Tarogong Kidul', 'Jl. Cimanuk Simpang Bunderan Tarogong', 'Jl. Cimanuk', 'Arteri Primer', 'Jalur Komuter (Daily Commuters)', -7.2185, 107.892, 'Static Billboard', 14, 7, 98, 1, 'Curved Corner (Sudut Simpang)', 200, 118000, 96000, 45, 18, 89, 84, 'Rendah (Unobstructed)', 'Available', '', 38000000, 10700, 'LED Spotlight 6x200W', 'Pintu masuk kota Garut dari arah Kadungora/Bandung', 'Wisatawan Cipanas Garut, Penikmat Dodol, Warga Priangan');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-1', 'Alun-Alun & Masjid Raya Bandung', 'Tourism & Leisure', -6.9213, 107.6186, 'SES A/B', 'Pusat wisata sejarah & pejalan kaki');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-01', 'poi-bdg-1', 450, 'Pusat wisata sejarah & pejalan kaki');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-2', 'Kantor Pusat Bank BJB & Koridor Finansial', 'CBD & Office', -6.9213, 107.6186, 'SES A/B', 'Pusat kantor perbankan & korporasi');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-01', 'poi-bdg-2', 200, 'Pusat kantor perbankan & korporasi');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-3', 'The Trans Luxury Hotel & Trans Studio Mall', 'Mall & Shopping', -6.9213, 107.6186, 'SES A/B', 'Mall keluarga & hotel bintang lima');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-01', 'poi-bdg-3', 1400, 'Mall keluarga & hotel bintang lima');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-4', 'Stasiun Kereta Api Bandung (KAI)', 'Transit Hub & Toll', -6.9213, 107.6186, 'SES A/B', 'Pintu gerbang kereta antar-kota');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-01', 'poi-bdg-4', 1800, 'Pintu gerbang kereta antar-kota');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-5', 'Gerbang Tol Pasteur (Tol Cipularang / Padaleunyi)', 'Transit Hub & Toll', -6.8924, 107.5794, 'SES A/B', 'Pintu masuk-keluar utama Jakarta-Bandung');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-02', 'poi-bdg-5', 150, 'Pintu masuk-keluar utama Jakarta-Bandung');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-6', 'Paris Van Java Resort Lifestyle Mall', 'Mall & Shopping', -6.8924, 107.5794, 'SES A/B', 'Tujuan belanja & kuliner utama turis');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-02', 'poi-bdg-6', 1600, 'Tujuan belanja & kuliner utama turis');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-7', 'Universitas Kristen Maranatha', 'Campus & School', -6.8924, 107.5794, 'SES A/B', 'Kampus swasta ternama Bandung Barat');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-02', 'poi-bdg-7', 850, 'Kampus swasta ternama Bandung Barat');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-8', 'BTC Fashion Mall & Hotel Pasteur Corridor', 'Mall & Shopping', -6.8924, 107.5794, 'SES A/B', 'Pusat belanja busana & hotel transit');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-02', 'poi-bdg-8', 400, 'Pusat belanja busana & hotel transit');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-9', 'Institut Teknologi Bandung (ITB Ganesha)', 'Campus & School', -6.8863, 107.6149, 'SES A/B', 'Pusat universitas teknik nomor satu');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-03', 'poi-bdg-9', 650, 'Pusat universitas teknik nomor satu');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-10', 'Kawasan Factory Outlet & Cafe Dago', 'Mall & Shopping', -6.8863, 107.6149, 'SES A/B', 'Hangout Gen-Z & wisata belanja');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-03', 'poi-bdg-10', 250, 'Hangout Gen-Z & wisata belanja');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-11', 'Rumah Sakit Borromeus Dago', 'Hospital & Health', -6.8863, 107.6149, 'SES A/B', 'Rumah sakit swasta rujukan');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-03', 'poi-bdg-11', 550, 'Rumah sakit swasta rujukan');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-12', 'Universitas Padjadjaran (Kampus Dipatiukur)', 'Campus & School', -6.8863, 107.6149, 'SES A/B', 'Pusat ribuan mahasiswa pascasarjana');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-03', 'poi-bdg-12', 900, 'Pusat ribuan mahasiswa pascasarjana');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-13', 'Riau Junction Supermarket & Mall', 'Mall & Shopping', -6.9084, 107.6138, 'SES A/B', 'Pusat belanja groceries premium keluarga');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-04', 'poi-bdg-13', 80, 'Pusat belanja groceries premium keluarga');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-14', 'Heritage Factory Outlet & Distro Hub', 'Mall & Shopping', -6.9084, 107.6138, 'SES A/B', 'Sentra fashion muda & turis akhir pekan');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-04', 'poi-bdg-14', 200, 'Sentra fashion muda & turis akhir pekan');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-15', 'Gedung Sate & Kantor Gubernur Jabar', 'CBD & Office', -6.9084, 107.6138, 'SES A/B', 'Pusat administrasi pemerintahan provinsi');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-04', 'poi-bdg-15', 950, 'Pusat administrasi pemerintahan provinsi');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-16', 'Banda Gourmet Dining Street', 'Tourism & Leisure', -6.9084, 107.6138, 'SES A/B', 'Kawasan restoran keluarga & eksekutif');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-04', 'poi-bdg-16', 350, 'Kawasan restoran keluarga & eksekutif');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-17', 'Lapangan Gasibu & Monumen Perjuangan', 'Tourism & Leisure', -6.9632, 107.6394, 'SES A/B', 'Pusat olahraga & event massal publik');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-05', 'poi-bdg-17', 300, 'Pusat olahraga & event massal publik');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-18', 'Pusat Perkantoran Telkom Landmark Tower Jabar', 'CBD & Office', -6.9632, 107.6394, 'SES A/B', 'Pusat industri digital & telekomunikasi');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-05', 'poi-bdg-18', 450, 'Pusat industri digital & telekomunikasi');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-19', 'Universitas Widyatama & Itenas', 'Campus & School', -6.9632, 107.6394, 'SES A/B', 'Koridor kampus mahasiswa Cikutra');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-05', 'poi-bdg-19', 1200, 'Koridor kampus mahasiswa Cikutra');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-20', 'Gerbang Tol Buah Batu (Tol Padaleunyi)', 'Transit Hub & Toll', -6.9149, 107.5996, 'SES A/B', 'Akses komuter Bandung Selatan & timur');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-06', 'poi-bdg-20', 750, 'Akses komuter Bandung Selatan & timur');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-21', 'Telkom University Smart Campus (Dayeuhkolot)', 'Campus & School', -6.9149, 107.5996, 'SES A/B', 'Kampus teknologi dengan 30.000+ mahasiswa');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-06', 'poi-bdg-21', 1800, 'Kampus teknologi dengan 30.000+ mahasiswa');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bdg-22', 'Metro Trade Center & Sentra Otomotif ByPass', 'Mall & Shopping', -6.9149, 107.5996, 'SES A/B', 'Dealer mobil & pusat suku cadang');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-06', 'poi-bdg-22', 600, 'Dealer mobil & pusat suku cadang');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-1', 'Summarecon Mall Bekasi (SMB)', 'Mall & Shopping', -6.8996, 107.6105, 'SES A/B', 'Mall gaya hidup terpadu & pusat kuliner');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-07', 'poi-bks-1', 350, 'Mall gaya hidup terpadu & pusat kuliner');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-2', 'Kompleks Pemkot Bekasi & Stadion Patriot', 'CBD & Office', -6.8996, 107.6105, 'SES A/B', 'Pusat pemerintahan kota & olahraga');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-07', 'poi-bks-2', 550, 'Pusat pemerintahan kota & olahraga');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-3', 'Gerbang Tol Bekasi Barat 1 & 2', 'Transit Hub & Toll', -6.8996, 107.6105, 'SES A/B', 'Akses utama komuter Jakarta-Cikampek');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-07', 'poi-bks-3', 650, 'Akses utama komuter Jakarta-Cikampek');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-4', 'Stasiun LRT Jabodebek Bekasi Barat', 'Transit Hub & Toll', -6.8996, 107.6105, 'SES A/B', 'Transit kereta layang harian ke Kuningan/Dukuh Atas');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-07', 'poi-bks-4', 700, 'Transit kereta layang harian ke Kuningan/Dukuh Atas');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-5', 'Ruas Jalan Tol Jakarta - Cikampek Layang MBZ', 'Transit Hub & Toll', -6.9421, 107.6622, 'SES A/B', 'Jalur komuter logistik & antar-kota terpadat di Asia');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-08', 'poi-bks-5', 0, 'Jalur komuter logistik & antar-kota terpadat di Asia');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-6', 'Metropolitan Mall Bekasi & Grand Metropolitan', 'Mall & Shopping', -6.9421, 107.6622, 'SES A/B', 'Pusat belanja modern tertua & teramai');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-08', 'poi-bks-6', 900, 'Pusat belanja modern tertua & teramai');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-7', 'Sentra Otomotif & Logistik Kalimalang', 'Industrial Estate', -6.9421, 107.6622, 'SES A/B', 'Gudang distribusi & dealer komersial');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-08', 'poi-bks-7', 1100, 'Gudang distribusi & dealer komersial');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-8', 'Plaza Cibubur & Cibubur Junction', 'Mall & Shopping', -6.2285, 106.9992, 'SES A/B', 'Mall persimpangan Bekasi-Bogor-Depok');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-09', 'poi-bks-8', 600, 'Mall persimpangan Bekasi-Bogor-Depok');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-9', 'Kawasan Residensial Elit CitraGran & Kota Wisata', 'Residential & Elite Housing', -6.2285, 106.9992, 'SES A/B', 'Hunian SES A/B dengan daya beli sangat tinggi');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-09', 'poi-bks-9', 400, 'Hunian SES A/B dengan daya beli sangat tinggi');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bks-10', 'Gerbang Tol Cibubur (Tol Jagorawi)', 'Transit Hub & Toll', -6.2285, 106.9992, 'SES A/B', 'Arus masuk ribuan mobil eksekutif tiap pagi');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-09', 'poi-bks-10', 850, 'Arus masuk ribuan mobil eksekutif tiap pagi');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-dpk-1', 'Margo City Mall & Depok Town Square (Detos)', 'Mall & Shopping', -6.252, 106.984, 'SES A/B', 'Pusat gaya hidup & retail no. 1 di Kota Depok');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-10', 'poi-dpk-1', 150, 'Pusat gaya hidup & retail no. 1 di Kota Depok');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-dpk-2', 'Universitas Indonesia (UI) Kampus Depok', 'Campus & School', -6.252, 106.984, 'SES A/B', 'Kampus terbesar Indonesia dengan 45.000+ civitas');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-10', 'poi-dpk-2', 450, 'Kampus terbesar Indonesia dengan 45.000+ civitas');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-dpk-3', 'Stasiun KRL Pondok Cina & UI', 'Transit Hub & Toll', -6.252, 106.984, 'SES A/B', 'Stasiun komuter commuterline Jakarta-Bogor');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-10', 'poi-dpk-3', 300, 'Stasiun komuter commuterline Jakarta-Bogor');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-dpk-4', 'Universitas Gunadarma Margonda', 'Campus & School', -6.252, 106.984, 'SES A/B', 'Kampus teknik komputer & ekonomi');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-10', 'poi-dpk-4', 400, 'Kampus teknik komputer & ekonomi');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-dpk-5', 'Gerbang Tol Margonda (Tol Cijago / Cengkareng-Kunciran)', 'Transit Hub & Toll', -6.2483, 106.9922, 'SES A/B', 'Akses lingkar luar menuju Bandara Soetta & Cibubur');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-11', 'poi-dpk-5', 500, 'Akses lingkar luar menuju Bandara Soetta & Cibubur');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-dpk-6', 'Pusat Kuliner & Restoran Keluarga Margonda', 'Tourism & Leisure', -6.2483, 106.9922, 'SES A/B', 'Ratusan gerai F&B nasional & internasional');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-11', 'poi-dpk-6', 200, 'Ratusan gerai F&B nasional & internasional');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-dpk-7', 'Pesona Square Mall Depok', 'Mall & Shopping', -6.2483, 106.9922, 'SES A/B', 'Mall modern keluarga & bioskop');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-11', 'poi-dpk-7', 800, 'Mall modern keluarga & bioskop');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bgr-1', 'Tugu Kujang & Monumen Landmark Kota Bogor', 'Tourism & Leisure', -6.184, 106.9772, 'SES A/B', 'Titik nol kilometer & ikon kebanggaan Bogor');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-12', 'poi-bgr-1', 50, 'Titik nol kilometer & ikon kebanggaan Bogor');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bgr-2', 'Botani Square Mall & IPB Convention Center', 'Mall & Shopping', -6.184, 106.9772, 'SES A/B', 'Pusat perbelanjaan paling prestisius di Bogor');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-12', 'poi-bgr-2', 200, 'Pusat perbelanjaan paling prestisius di Bogor');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bgr-3', 'Institut Pertanian Bogor (IPB Baranangsiang)', 'Campus & School', -6.184, 106.9772, 'SES A/B', 'Kampus pascasarjana & riset agribisnis');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-12', 'poi-bgr-3', 250, 'Kampus pascasarjana & riset agribisnis');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bgr-4', 'Terminal Baranangsiang & Exit Tol Jagorawi', 'Transit Hub & Toll', -6.184, 106.9772, 'SES A/B', 'Pintu gerbang utama keluar tol Jagorawi');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-12', 'poi-bgr-4', 350, 'Pintu gerbang utama keluar tol Jagorawi');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bgr-5', 'Pintu Tol Ciawi / Gadog (Tol Jagorawi KM 44)', 'Transit Hub & Toll', -6.6015, 106.8049, 'SES A/B', 'Titik awal jalur liburan wisata Puncak');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-13', 'poi-bgr-5', 200, 'Titik awal jalur liburan wisata Puncak');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bgr-6', 'Kawasan Wisata Puncak & Villa Resort', 'Tourism & Leisure', -6.6015, 106.8049, 'SES A/B', 'Destinasi liburan keluarga Jakarta & domestik');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-13', 'poi-bgr-6', 500, 'Destinasi liburan keluarga Jakarta & domestik');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-bgr-7', 'Sentra Kuliner Oleh-oleh & Restoran Sunda Gadog', 'Tourism & Leisure', -6.6015, 106.8049, 'SES A/B', 'Tempat singgah puluhan ribu kendaraan per hari');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-13', 'poi-bgr-7', 150, 'Tempat singgah puluhan ribu kendaraan per hari');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-krw-1', 'Kawasan Industri Karawang International Industrial City (KIIC)', 'Industrial Estate', -6.6631, 106.8574, 'SES A/B', 'Pabrik manufaktur Toyota, Daihatsu, Yamaha, Sharp');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-14', 'poi-krw-1', 300, 'Pabrik manufaktur Toyota, Daihatsu, Yamaha, Sharp');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-krw-2', 'Gerbang Tol Karawang Barat (Tol Jakarta-Cikampek)', 'Transit Hub & Toll', -6.6631, 106.8574, 'SES A/B', 'Gerbang ribuan kendaraan logistik & mobil pimpinan');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-14', 'poi-krw-2', 450, 'Gerbang ribuan kendaraan logistik & mobil pimpinan');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-krw-3', 'Resinda Park Mall Karawang', 'Mall & Shopping', -6.6631, 106.8574, 'SES A/B', 'Mall terbesar & hotel bintang empat Karawang');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-14', 'poi-krw-3', 1800, 'Mall terbesar & hotel bintang empat Karawang');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-krw-4', 'Stasiun Kereta Cepat Whoosh Karawang', 'Transit Hub & Toll', -6.6631, 106.8574, 'SES A/B', 'Stasiun kereta cepat Jakarta-Bandung');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-14', 'poi-krw-4', 3500, 'Stasiun kereta cepat Jakarta-Bandung');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-crb-1', 'Cirebon Super Block Mall (CSB Mall)', 'Mall & Shopping', -6.5982, 106.8088, 'SES A/B', 'Mall no. 1 di Wilayah III Cirebon & Pantura');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-15', 'poi-crb-1', 100, 'Mall no. 1 di Wilayah III Cirebon & Pantura');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-crb-2', 'Kawasan Bisnis & Perbankan Jl. Cipto', 'CBD & Office', -6.5982, 106.8088, 'SES A/B', 'Jantung ekonomi & pertokoan modern kota Cirebon');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-15', 'poi-crb-2', 200, 'Jantung ekonomi & pertokoan modern kota Cirebon');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-crb-3', 'Stasiun Kereta Api Cirebon Kejaksan', 'Transit Hub & Toll', -6.5982, 106.8088, 'SES A/B', 'Stasiun persimpangan jalur lintas utara & selatan Jawa');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-15', 'poi-crb-3', 1500, 'Stasiun persimpangan jalur lintas utara & selatan Jawa');
INSERT OR IGNORE INTO points_of_interest (poi_id, name, category, latitude, longitude, target_ses, highlight_text) VALUES ('poi-crb-4', 'Sentra Wisata Kuliner Empal Gentong & Batik Trusmi', 'Tourism & Leisure', -6.5982, 106.8088, 'SES A/B', 'Daya tarik turis domestik lintas Jawa');
INSERT INTO spot_poi_distances (spot_id, poi_id, distance_meters, highlight_text) VALUES ('spot-15', 'poi-crb-4', 1200, 'Daya tarik turis domestik lintas Jawa');

PRAGMA foreign_keys = ON;
